package mapeamentos;
// Generated 25/07/2021 21:55:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,schema="public"
)
public class Clientes  implements java.io.Serializable {


     private int idCliente;
     private String nomeCliente;
     private Set contas = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(int idCliente) {
        this.idCliente = idCliente;
    }
    public Clientes(int idCliente, String nomeCliente, Set contas) {
       this.idCliente = idCliente;
       this.nomeCliente = nomeCliente;
       this.contas = contas;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_cliente", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nome_cliente", length=30)
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set getContas() {
        return this.contas;
    }
    
    public void setContas(Set contas) {
        this.contas = contas;
    }




}


